name: Nautical Pioneer
favicon: null
layout_spectrum: 0.9208561775740236
typography_spectrum: 0.8600738036911935
title: The Nautical Pioneer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#38393b'
    - '#adaeae'
    - '#5e5f61'
    - '#8e8f91'
  brandStrength: 0
  lightness: 0.2609118134714663
  saturation: 0.6545627196319401
  rhythmicContrast: 0.7795492878649384
purpose: []
