name: Nautical Pioneer
favicon: null
layout_spectrum: 0.9208561775740236
typography_spectrum: 0.8600738036911935
title: The Nautical Pioneer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.16320772329345345
  lightness: 0.2609118134714663
  saturation: 0.6545627196319401
  rhythmicContrast: 0.7795492878649384
purpose: []
