name: Nautical Pioneer
favicon: null
layout_spectrum: 0.862612
typography_spectrum: 0.18917
title: The Nautical Pioneer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0C0'
    - '#285880'
    - '#888880'
    - '#3078A8'
    - '#000000'
  brandStrength: 0
  lightness: 0.2609118134714663
  saturation: 0.6545627196319401
  rhythmicContrast: 0.7795492878649384
purpose: []
